# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: source-ip

env:
  GO_VERSION: 1.24.3

on:
  push:
    branches: [ "master", "feature/source-ip" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    # - name: Build
      # run: go build -v ./...

    - name: Build
      run: make build-source-ip

  build-and-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')  # Only run on version tags
    needs: build
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build Linux AMD64 Binary
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: 0
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/}
        
        # Build the binary with version info
        go build -ldflags="-s -w -X main.version=${VERSION}" -o source-ip-linux-amd64 ./...
        
        # Make it executable
        chmod +x source-ip-linux-amd64
        
        # Create a compressed archive
        tar -czf source-ip-${VERSION}-linux-amd64.tar.gz source-ip-linux-amd64
        
        # Generate checksums
        sha256sum source-ip-linux-amd64 > source-ip-${VERSION}-linux-amd64.sha256
        sha256sum source-ip-${VERSION}-linux-amd64.tar.gz >> source-ip-${VERSION}-linux-amd64.sha256

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          source-ip-linux-amd64
          source-ip-*-linux-amd64.tar.gz
          source-ip-*-linux-amd64.sha256
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
