# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: source-ip

env:
  GO_VERSION: 1.24.3

on:
  push:
    branches: [ "master", "feature/source-ip" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    # - name: Build
      # run: go build -v ./...

    - name: Build
      run: make build-source-ip
