name: source-ip

env:
  GO_VERSION: 1.24.3

on:
  push:
    branches: [ "master", "feature/source-ip" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build
      run: make build-source-ip

  build-and-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')  # Only run on version tags
    needs: build
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build Linux ARM64 binary
      env:
        GOOS: linux
        GOARCH: arm64
        CGO_ENABLED: 0
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/}

        cd source-ip 
        go build -ldflags="-s -w -X main.version=${VERSION}" -o ../source-ip-linux-arm64 .
        cd ..
        chmod +x source-ip-linux-arm64
        zip source-ip-${VERSION}-linux-arm64.zip source-ip-linux-arm64
        sha256sum source-ip-linux-arm64 > source-ip-${VERSION}-linux-arm64.sha256
        sha256sum source-ip-${VERSION}-linux-arm64.zip >> source-ip-${VERSION}-linux-arm64.sha256

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          source-ip-linux-arm64
          source-ip-*-linux-arm64.zip
          source-ip-*-linux-arm64.sha256
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}